dist: xenial
sudo: required
language: java
notifications:
  slack:
    secure: c8TGIgFUIwQm/b4LKRjyqs+Lw4QCg2nd6lnwxjwsJKCJBUmJp5Pf+h8rznXJUglxytYWoLZQ7NFuFyt85L1RQQxK+rWeRn6mddEr5gR3vXJUvYycPAIWDGfVVkSsKdPVyxgbmlrSxbThB4lMHIeUUzE4ITTb9IyXxPcvTHSBPQVpED/MlJgYLucRKHpUbvNn8Bj+bKECDzbNoZTLc7gXDPIi3ejazLC2BYzxHfk52b7O18LhLMWVra8fccxlr1sBzprrzTKj10yDXrzuyv8YOcFTs/ru8wZyz+8hPk97KBk1wyEN7mFhFVPlTQP/cOMYUMM/iflWLV2iR0gmg7Y5LrBauR0CkLW30KOLR9p4B4Ygp5CuJPxrniYfKUXlB1KyUPLlDjMc8/CZ8Aunc4SniZqDg8Ow4vix/3PebGj+2rwjDL7KizMzxNSQa0ieMEUxgiWnPl5ZY8zXUkklHH+x7sB9aX3UpElnfREbq9d9w2Ak6EwvANTds4lPScieOY1gntvTCfcEethR3mMEY9vT4R9+ZXF54RKogbBFG89k+1J2Dv0rI8ZZTpwYIkNWHpxfIeKz4jekOm0lFJE/8/zWIgyZEZSqIi6GhfiFaEUzOKXG295VfDhE5KF+uzXVHeWPA8Hgy1aggCtXc/hBam3L8Ec2gaSEU547MNuLOMQkEhY=
jdk:
- openjdk8
- openjdk11
services:
- docker
before_install:
- if [ $(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p') -gt 1 ] ; then export JAVA_VERSION_BUILD=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p'); export JAVA_VERSION=$JAVA_VERSION_BUILD; else export JAVA_VERSION_BUILD=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*)\.([0-9])\.([0-9]).*$/\1.\2/p'); export JAVA_VERSION=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*)\.([0-9])\.([0-9]).*$/\1.\2.\3/p'); fi;
- gem install asciidoctor
- "./.travis/install_yq.sh"
install:
- mvn -q install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- "./.travis/setup-kubernetes.sh"
- "./.travis/setup-helm.sh"
script:
- "./.travis/build.sh"
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - COMMIT=${TRAVIS_COMMIT::8}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-master}
  - DOCKER_ORG=strimzici
  - DOCKER_REGISTRY=docker.io
  - TEST_CLUSTER=minikube
  - TEST_KUBECTL_VERSION=v1.16.0
  - TEST_NSENTER_VERSION=2.32
  - TEST_HELM2_VERSION=v2.16.3
  - TEST_HELM3_VERSION=v3.2.0
  - TEST_MINIKUBE_VERSION=v1.2.0
  - STRIMZI_DEFAULT_LOG_LEVEL=DEBUG
  - MVN_ARGS="-q -Dsurefire.rerunFailingTestsCount=5 -Dfailsafe.rerunFailingTestsCount=2"
  - DOCKER_BUILD_ARGS="-q"
  - secure: 4Y7PZWQEBGvGGyDyPYXY8ZbTWjD9O7kvrkKfXq0hfM7DmId7EfkGLXf6u/gp9/YWBW5cgl9svWjVwZmIHJq08MJ3x7FLyZz34++nnkSUbTkiUcPeSekO/RecALgkG/wh3WQZZwNTq6Fh61f2d1cn/2x9MwtXE1DjZIgTWOz/H8O4w/vEaxZYRCz/Flih87/QcFrQ9wooVf0if6r+UiFCSizgU+pxBgpO73Sg7x3uy3dB0ubzSpSThnoGevTAhfVzmoRO5FSKjGSF2/mvG14b5hUHZv3gm7Ch8D3crVco3Ima5SsD9V8jOK1jUmy6eVlrsuWPmahd7xoRJfUqavchct2tBMe44mgcbf/UG9+p1n0x/3I754mJLNAOT53mdPjoL/KX2yvHnVcZwq5R1nli3zJxdEyHMocB9Pj8v4ohCEfNf0Mwe78BfVbrqxpnoV7lvy1SF1sqqCVaYrghH5tMzaGC/aivZXu5iDidHBhuqtRm8MTR18RMa0r20nRh/zLG0HJuLQlNCRXoQUmpSwp7FSPvn+cILWSLdMEqabIda/ey8FgxkuBZ+zFVgqTppxTxBwaPQzvBdALSEe6lTyJwy4jnKtZFdpa4v1CRGjEAmewB2ZRfeTvpaeagxLOJgZlrEDHYLCl4TkSU1dny6jMXSpuEVjPE1ZnvGjcWVMb5Yr4= # DOCKER_USER
  - secure: Xwy5PG+TlRkTsGyelG/d0N+aVUQKM8wa/um6LSbEBd0nUc6WRZ36BrP4FI71hdknCrr9/1oDYkMt2FD20F9fzJJeT9vPGl7pd3kufTiZvqKphYRhHrjRGOWIoQAMRrcQOKUKGu9mcaeXtstdNbcRMmBbztu5y+IDtPfC5qJol2eXFMhkT0eZ0gkSFDKMJNzup35HbAnVu6KlqOVNxDHE5VhaMKl3BaLIO6GuqNwaRvG8nf/zikS+ZoVHa/fGfIOqPBjhHkyGTgrf4X0/QLPCO5mEzR97WGh8J3fKYXR9vNGo9ff/d3yfyFKkqkp0bJHruWMghTuFsJDAnQAo5dhA85f8zd9COTVLkYBxW0Aibs4i0pbVg0JlgfLhT5dyrPqzq8Xp00AvH23Oqbn5me4WL2kLsB2R+PM8s+IyDZO+ZfLM2VHPt5ogRCgmMEzfSibvzKz1p0s3z/sw+Qr/chRe0qbfh6u4XaLvUnXLza5YkmILkRsmSDrZQYDSPYutvDqQlno/h02um7h0kNJQfIwRi/pVDGkTzpBkWYohkL6a71CW4aXIRgI+UOmY1+383FStDN6sfjInJ7nerG+cWzEyDwBxZ7e50R3CHjunt6StKueh4HUrNQfOIFKllhTOoiFNPdX/xQYjfdm4szTtISMMsiz6ht81/G1B7+/d2TNTa/U= # DOCKER_PASS
  - secure: wLNuKwwziqNyvZTpn8+uRJKkn8P8e0+CNLysCMA1ijtNYzCTlhnpzPvFiHEXmhGvFjhNuWkXXlVhmemzaFSZHxEyM/FLVXzKl782KQM9+uKx2jsvUemgqzA+SQyIqvjJYEMtg81UOXFkfnvAD1dtNdW8GcPW5/MREtcmSw9m7MfzeKigCKXnjiA772NA0fW2jiJaIHOMsp/7M+7IWX1a/U8F2Ta0BlvuZ/OYB66Ln4yfIVQ2HUZRGcuJzuQA+gbJzbnEAJqoAUAV7+AIY7qYG8igE1kYtYpJssnDQuMLMtrVmkaa4i6SelIMi1QjqyACNNC/3gsbtbYySPh+1o5JQwQLmI2hjo/A/v4a3lYFjTF4+4CtkHswUzBOgWR+g5lBPnxwpEc7sg4wuvJzw3dpZA3xJ0SotGyZQnNsXt+LbTKQlw1QVoho5CtpomxXX0D0y1aKl5JFR6wnBV5YovhWpdYOIQ2K9LbOIGX0YIvERXHS/lawYarnWimiIzvKFwRZy9xtlJtZYJoiJd/DqO6+CkyV+AujxPBgvEVZd/OfODIuWS+NRXUzeOxtIBSziZ73aqCHsO2GXH4VfsHy22xRzkGuAIpOIb+zpZAPnseiy+NJ4NHJemhvzE2VXncls4StUQWgaEir0GweaZPqL6QDRAN9gsPGxzZXRVyPXnYFXJ0= # Maven publishing
  - secure: NCFc6zJrb8MpNhcnjkYYzQe0nk2ui0vgeBswkrxpOVLMEJxmcM53OabWLK0pW9VGdWMFMr9gndX8zOXyablMhTxUPsEbDZ4IZJr1MNdvFbx7qoohrKQ8nYYU6y73vuAf6p1NyrqOTAp2Ow9bI/boMLmhKvDKZ2dqlJDsJOF4e797wv8ZPXVpMgTcZE2n1zCA1MV3vWsJeoz5EgRrc0O/D/NmOBnQYrn5NiT3h33wFvApVEv/z/KYBWu15mx9mePw6OhEFv/+dcOHw1t6DK4WwtC5kZuDE+yTEz4il5R9QsG2J2uXenXRfACYcwVbRTlXSyELnDpmbrJDCrWdrv0k4pSxdUjZJkqXORK6kVkjq03tD85bYv76S0cI1D73ezn5tj/4PSRDL6j47hnQtGsiVGnJ0XuwAuGi9eXiL84ROblkyjUgF2ZniEYQdg0Kg5WDJXIRD3D7gL3CkQ4bfLFzgl1HQLMYPFmHrWVt7rMzWjFxKHFt6cS7HSTJVr5nFudPvQ4Ozzl56asMnV5eNqksGdSioKeL65x1S2VihKeZOViHH9vIIOU39kJNMlFRf1j+7zewboFOGkA9UKnt9aK9n6fjFm5BrpDwRZoqOfq1raKwux/cxs774ZGE3AfVVvH6rw/xxdQjj0m76Qp+nLlJXAbVbiXD6+lx/22u2d7D9T0= # Maven publishing
  - secure: pVE+P4F7b14BhGBUXYhPiTBYwsWj50jOQ76Lwae5IcWFKB8Ibrr8bvIW/bLfnsjVv51d0Bf0vyGRHoW2V2POC6n1wkzE3nHZ+lSJQkmg5jsqr9z4Nxd6EsZUpwlSBC7/hzlqbE8GeBeIg5qxoclInZrcG+zoTgcfA1N/hIooNniP3TE1jBkRueYptvAiG8ugL9IwbQ8UvXXE9GVHkROwax4AOEFG7ZjWDzOH2pzvGtvT34pPDGtL0ZYWwbklZsdkCkFmHR0Lo8vQi1sesqi3KmiqStlrRfEHw+RgRhk2tgB76AzIyUO4zOX0+nGqKWwfTGt933/19ENrg+uKJr1j57N9Cwzh2xxRGlwUi44c64lmOCMtWedU+xAF8omVvoOuqYibDTeNPm8lYaiV0JWoxrJ9vKwh3jEyi9lbUmYpU7I+Pi5SC2crQQQDYH/Qfd+gKY/V7QfCKfjjneKe/TA0uXBrHTv07E+WLGcLFVQ6ir3cvzk1lU5iyH2cR1mfCMY5/DN7EQQOJn5Ww1dwyJBPvJkBGHV/hR3QZUWtcE7nuvmbrFMZQBLzlnYuZfMtdRuyU8dOUtsDrt0On1A1JswvOfwAqSyitQ7mAUlq2mqazMRTNFmj8zVPZ12IWuMsEw4zTc16RAedszME166B2fp9PEMF4oErGlHxoBqhrpanyO0= # Maven publishing
