apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-drain-cleaner
  labels:
    app: strimzi-drain-cleaner
  namespace: strimzi-drain-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-drain-cleaner
  template:
    metadata:
      labels:
        app: strimzi-drain-cleaner
    spec:
      serviceAccountName: strimzi-drain-cleaner
      containers:
        - name: strimzi-drain-cleaner
          image: quay.io/strimzi/drain-cleaner:1.2.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          env:
            - name: STRIMZI_DRAIN_KAFKA
              value: "true"
            - name: STRIMZI_DRAIN_ZOOKEEPER
              value: "true"
            - name: STRIMZI_DENY_EVICTION
              value: "true"
            - name: STRIMZI_CERTIFICATE_WATCH_ENABLED
              value: "true"
            - name: STRIMZI_CERTIFICATE_WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_CERTIFICATE_WATCH_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - /opt/strimzi/bin/drain_cleaner_run.sh
          volumeMounts:
            - name: webhook-certificates
              mountPath: "/etc/webhook-certificates"
              readOnly: true
            - name: tmp-dir
              mountPath: "/tmp"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: webhook-certificates
          secret:
            secretName: strimzi-drain-cleaner
        - name: tmp-dir
          emptyDir: {}
  strategy:
    type: RollingUpdate
