# Default values for strimzi-kafka-operator.

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`), 
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: false

image:
  repository: strimzi
  name: operator
  tag: 0.17.0
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local

tolerations: []
affinity: {}
nodeSelector: {}


# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
zookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
kafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
kafkaConnect:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
kafkaConnects2i:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
topicOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.17.0
userOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.17.0
kafkaInit:
  image:
    repository: strimzi
    name: operator
    tag: 0.17.0
tlsSidecarZookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
tlsSidecarKafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
tlsSidecarEntityOperator:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
kafkaMirrorMaker:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
kafkaBridge:
  image:
    repository: strimzi
    name: kafka-bridge
    tag: 0.15.2
kafkaExporter:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
jmxTrans:
  image:
    repository: strimzi
    name: jmxtrans
    tag: 0.17.0
kafkaMirrorMaker2:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.17.0
resources:
  limits:
    memory: 256Mi
    cpu: 1000m
  requests:
    memory: 256Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker image repository used by all Strimzi images
# imageRepositoryOverride: foobar
# Override the docker image tag used by all Strimzi images
# imageTagOverride: latest
createGlobalResources: true
