apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: strimzi
    strimzi.io/crd-install: "true"
  name: kafkatopics.kafka.strimzi.io
spec:
  conversion:
    strategy: None
  group: kafka.strimzi.io
  names:
    categories:
    - strimzi
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    shortNames:
    - kt
    singular: kafkatopic
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the Kafka cluster this topic belongs to
      jsonPath: .metadata.labels.strimzi\.io/cluster
      name: Cluster
      type: string
    - description: The desired number of partitions in the topic
      jsonPath: .spec.partitions
      name: Partitions
      type: integer
    - description: The desired number of replicas of each partition
      jsonPath: .spec.replicas
      name: Replication factor
      type: integer
    - description: The state of the custom resource
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1beta2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The specification of the topic.
            properties:
              config:
                description: The topic configuration.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              partitions:
                description: The number of partitions the topic should have. This cannot be decreased after topic creation. It can be increased after topic creation, but it is important to understand the consequences that has, especially for topics with semantic partitioning. When absent this will default to the broker configuration for `num.partitions`.
                minimum: 1
                type: integer
              replicas:
                description: The number of replicas the topic should have. When absent this will default to the broker configuration for `default.replication.factor`.
                maximum: 32767
                minimum: 1
                type: integer
              topicName:
                description: The name of the topic. When absent this will default to the metadata.name of the topic. It is recommended to not set this unless the topic name is not a valid Kubernetes resource name.
                type: string
            type: object
          status:
            description: The status of the topic.
            properties:
              conditions:
                description: List of status conditions.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      type: string
                    message:
                      description: Human-readable message indicating details about the condition's last transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition (a single word in CamelCase).
                      type: string
                    status:
                      description: The status of the condition, either True, False or Unknown.
                      type: string
                    type:
                      description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: The generation of the CRD that was last reconciled by the operator.
                type: integer
              topicName:
                description: Topic name.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: The name of the Kafka cluster this topic belongs to
      jsonPath: .metadata.labels.strimzi\.io/cluster
      name: Cluster
      type: string
    - description: The desired number of partitions in the topic
      jsonPath: .spec.partitions
      name: Partitions
      type: integer
    - description: The desired number of replicas of each partition
      jsonPath: .spec.replicas
      name: Replication factor
      type: integer
    - description: The state of the custom resource
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The specification of the topic.
            properties:
              config:
                description: The topic configuration.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              partitions:
                description: The number of partitions the topic should have. This cannot be decreased after topic creation. It can be increased after topic creation, but it is important to understand the consequences that has, especially for topics with semantic partitioning. When absent this will default to the broker configuration for `num.partitions`.
                minimum: 1
                type: integer
              replicas:
                description: The number of replicas the topic should have. When absent this will default to the broker configuration for `default.replication.factor`.
                maximum: 32767
                minimum: 1
                type: integer
              topicName:
                description: The name of the topic. When absent this will default to the metadata.name of the topic. It is recommended to not set this unless the topic name is not a valid Kubernetes resource name.
                type: string
            type: object
          status:
            description: The status of the topic.
            properties:
              conditions:
                description: List of status conditions.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      type: string
                    message:
                      description: Human-readable message indicating details about the condition's last transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition (a single word in CamelCase).
                      type: string
                    status:
                      description: The status of the condition, either True, False or Unknown.
                      type: string
                    type:
                      description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: The generation of the CRD that was last reconciled by the operator.
                type: integer
              topicName:
                description: Topic name.
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: The name of the Kafka cluster this topic belongs to
      jsonPath: .metadata.labels.strimzi\.io/cluster
      name: Cluster
      type: string
    - description: The desired number of partitions in the topic
      jsonPath: .spec.partitions
      name: Partitions
      type: integer
    - description: The desired number of replicas of each partition
      jsonPath: .spec.replicas
      name: Replication factor
      type: integer
    - description: The state of the custom resource
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The specification of the topic.
            properties:
              config:
                description: The topic configuration.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              partitions:
                description: The number of partitions the topic should have. This cannot be decreased after topic creation. It can be increased after topic creation, but it is important to understand the consequences that has, especially for topics with semantic partitioning. When absent this will default to the broker configuration for `num.partitions`.
                minimum: 1
                type: integer
              replicas:
                description: The number of replicas the topic should have. When absent this will default to the broker configuration for `default.replication.factor`.
                maximum: 32767
                minimum: 1
                type: integer
              topicName:
                description: The name of the topic. When absent this will default to the metadata.name of the topic. It is recommended to not set this unless the topic name is not a valid Kubernetes resource name.
                type: string
            type: object
          status:
            description: The status of the topic.
            properties:
              conditions:
                description: List of status conditions.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      type: string
                    message:
                      description: Human-readable message indicating details about the condition's last transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition (a single word in CamelCase).
                      type: string
                    status:
                      description: The status of the condition, either True, False or Unknown.
                      type: string
                    type:
                      description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: The generation of the CRD that was last reconciled by the operator.
                type: integer
              topicName:
                description: Topic name.
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
