apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: strimzi
    strimzi.io/crd-install: "true"
  name: kafkaconnectors.kafka.strimzi.io
spec:
  conversion:
    strategy: None
  group: kafka.strimzi.io
  names:
    categories:
    - strimzi
    kind: KafkaConnector
    listKind: KafkaConnectorList
    plural: kafkaconnectors
    shortNames:
    - kctr
    singular: kafkaconnector
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the Kafka Connect cluster this connector belongs to
      jsonPath: .metadata.labels.strimzi\.io/cluster
      name: Cluster
      type: string
    - description: The class used by this connector
      jsonPath: .spec.class
      name: Connector class
      type: string
    - description: Maximum number of tasks
      jsonPath: .spec.tasksMax
      name: Max Tasks
      type: integer
    - description: The state of the custom resource
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1beta2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The specification of the Kafka Connector.
            properties:
              class:
                description: The Class for the Kafka Connector.
                type: string
              config:
                description: 'The Kafka Connector configuration. The following properties cannot be set: connector.class, tasks.max.'
                type: object
                x-kubernetes-preserve-unknown-fields: true
              pause:
                description: Whether the connector should be paused. Defaults to false.
                type: boolean
              tasksMax:
                description: The maximum number of tasks for the Kafka Connector.
                minimum: 1
                type: integer
            type: object
          status:
            description: The status of the Kafka Connector.
            properties:
              conditions:
                description: List of status conditions.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      type: string
                    message:
                      description: Human-readable message indicating details about the condition's last transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition (a single word in CamelCase).
                      type: string
                    status:
                      description: The status of the condition, either True, False or Unknown.
                      type: string
                    type:
                      description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      type: string
                  type: object
                type: array
              connectorStatus:
                description: The connector status, as reported by the Kafka Connect REST API.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              observedGeneration:
                description: The generation of the CRD that was last reconciled by the operator.
                type: integer
              tasksMax:
                description: The maximum number of tasks for the Kafka Connector.
                type: integer
              topics:
                description: The list of topics used by the Kafka Connector.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.tasksMax
        statusReplicasPath: .status.tasksMax
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
